spring:
  data:
    mongodb:
      uri: mongodb://localhost:270174/userdb
      database: userdb
      #uri: mongodb+srv://shbrkp_db_user:Vomjpr3XCe9dwlpx@user-ecom.ndirevd.mongodb.net/userdb?retryWrites=true&w=majority&appName=user-ecom
  application:
    name: user-service

build:
  id: 101
  version: v101
  name: "dev-build1"
  type: "development build"


#  datasource:
#    url: jdbc:postgresql://localhost:5432/userdb
#    username: shbrkp
#    password: shbrkp
#  jpa:
#    datasource: POSTGRESQL
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#      database-platform: org.hibernate.dialect.PostgreSQLDialect
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true
#uri: mongodb://localhost:27017/uqsersdb
server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

