spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    datasource: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.PostgreSQLDialect
#  h2:
#    console:
#      enabled: true
#    datasource:
#      url: jdbc:h2:mem:test
#    jpa:
#      show-sql: true
#      hibernate:
#        ddl-auto: create
#      properties:
#        hibernate:
#          format_sql: true



server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
